alias dk="docker"
alias dknls="dk network ls"
alias dkps="dk ps"
alias dkpsr="dk ps --filter status=running"
alias dkb="dk build . -t"
alias dkl="dk logs"
alias dkrmi="dk rmi -f"
alias dki="docker info"
alias dks="docker stats"
alias dkit="docker image tag"
alias dkip="docker image push"
alias dkils="docker image ls"
alias dklogin="docker login -u"