alias dk="docker"
alias dknls="dk network ls"
alias dkps="dk ps"
alias dkpsr="dk ps --filter status=running"
alias dkb="dk build . -t"
alias dkl="dk logs"
alias dkrmi="dk rmi -f"
alias dki="docker info"