# Git
alias gp='git pull --prune'
alias gst='git status -sb'
alias gr="git reset 'HEAD@{1}'"
alias gb="git branch $1"
alias gd="git diff --color | diff-so-fancy"
alias gcount="git rev-list HEAD --count"
alias gcm="git checkout master"
alias gcl="git clean"
alias gc="git commit -a"
alias gbd="git branch -D $1"
alias gch="git checkout $1"
alias grh="git reset --hard $1"
alias grs="git reset --soft $1"
alias grhh="git reset --hard HEAD^0"
alias gpu="git push origin $1"
alias gpm="git push origin master"
alias guo="git remote update origin --prune"
alias gm="git commit -am "$1""
alias grl="git ls-remote"
alias grm="git status | grep deleted | awk '{\$1=\$2=\"\"; print \$0}' | \perl -pe 's/^[ \t]*//' | sed 's/ /\\\\ /g' | xargs git rm"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
