alias gpush='git push'
alias gpull='git pull'
alias gfp='git fetch --prune'
alias gf='git fetch'
alias gst='git status -sb'
alias grh0="git reset HEAD~0"
alias gb="git branch"
alias gs="git stash"
alias gsa="git stash apply"
alias gd="git diff --color | diff-so-fancy"
alias gcount="git rev-list HEAD --count"
alias gcm="git checkout master"
alias gcl="git clean"
alias gca="git commit -a"
alias grhh="git reset --hard HEAD^0"
alias gpm="git push origin master"
alias guo="git remote update origin --prune"
alias grl="git ls-remote"
alias gra="git reset"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gadd="git add"
alias gcamend="git commit --amend"
alias gcam="git commit -am"
alias grh="git reset --hard"
alias grs="git reset --soft"
alias gbd="git branch -D"
alias gbed="git branch --edit-description"
alias gpo="git push origin"
alias gri="git rebase -i"
alias grih="git rebase -i HEAD~"
alias gr="git rebase"
alias grf="git reset"
alias gsh="git shortlog | grep -E '^[ ]+\w+' | wc -l"
alias gu="git shortlog | grep -E '^[^ ]'"
alias gt="git log --graph --all --since="yesterday.midnight" --until=midnight --author=\"$(git config user.name)\" --oneline"
alias grm="git status | grep deleted | awk '{\$1=\$2=\"\"; print \$0}' | \perl -pe 's/^[ \t]*//' | sed 's/ /\\\\ /g' | xargs git rm"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias ghist="git log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short"
