# Kubernetes
alias k8ci="kubectl cluster-info"
alias k8gd="kubectl get deployments"
alias k8gpn="kubectl get pods -n"
alias k8gpa="kubectl get pods --all-namespaces"
alias k8gc="kubectl config get-contexts"
alias k8gpw="kubectl get pods -o wide"
alias k8dp="kubectl describe pods"
alias k8gs="kubectl get services"
alias k8a="kubectl apply -f"