alias wts="date '+its %H:%M oclock' | say"
alias lfunctions="listFunctions"
alias laliases="listAliases"
alias cl='clear'
alias killbird='killall bird'
alias sctl="sysctl -a"
alias rsynca="rsync -arv"
alias clipboard="pbcopy <"
alias keygenssh="ssh-keygen -t ed25519 -C"