# Generated by Powerlevel10k configuration wizard on 2024-01-01
# Basic configuration with popular options
# https://github.com/romkatv/powerlevel10k

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'        ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

# Instant prompt mode
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Basic prompt settings
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

# Left prompt segments
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir                     # current directory
  vcs                     # git status
  command_execution_time  # previous command duration
  virtualenv             # python virtual environment
  status                 # exit code of the last command
  newline                # \n
  prompt_char           # prompt symbol
)

# Right prompt segments
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  time                  # current time
  ram                   # free RAM
  load                  # CPU load
  battery               # internal battery
)

# Directory settings
typeset -g POWERLEVEL9K_DIR_BACKGROUND='blue'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='black'
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'

# VCS settings
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='red'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'

# Prompt character
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='green'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='red'

# Time format
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# Restore previous options
'builtin' 'setopt' ${p10k_config_opts[@]}